// Generated by Selenium IDE
package junit;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  WebDriver driver;
  
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    driver.get("https://www.facebook.com/");
  }
 
  @Test
  public void test1() {
    
   driver.findElement(By.xpath("//*[@id=\"u_0_0_K1\"]")).click();
    driver.findElement(By.id("u_0_0_KE")).click();
    driver.findElement(By.id("u_2_8_iM")).sendKeys("rahul");
    driver.findElement(By.id("u_2_a_Sa")).click();
    driver.findElement(By.id("u_2_a_Sa")).sendKeys("mr");
    driver.findElement(By.id("day")).click();
    {
      WebElement dropdown = driver.findElement(By.id("day"));
      dropdown.findElement(By.xpath("//option[. = '17']")).click();
    }
    {
      WebElement element = driver.findElement(By.id("year"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("password_step_input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("password_step_input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("reg_form_box")).click();
    {
      WebElement dropdown = driver.findElement(By.id("year"));
      dropdown.findElement(By.xpath("//option[. = '2017']")).click();
    }
    driver.findElement(By.cssSelector(".\\_5k_2:nth-child(2) #sex")).click();
    driver.findElement(By.id("u_2_h_KH")).click();
    driver.findElement(By.id("u_2_h_KH")).sendKeys("7592889080");
    driver.findElement(By.id("password_step_input")).click();
    driver.findElement(By.id("password_step_input")).sendKeys("machingal");
    driver.findElement(By.id("u_2_n_ZD")).click();
  }
}
